# Texte für Prüfungen und Audit (Deutsch/Englisch). Platzhalter {0}, {1} ... für -f.
# Sprache: $script:EdepLanguage ('de' | 'en'), Standard nach Windows-Anzeigesprache.

$script:EdepLanguage = if ((Get-UICulture).TwoLetterISOLanguageName -eq 'de') { 'de' } else { 'en' }

function Set-EdepLanguage([ValidateSet('de', 'en')][string]$Language) {
    $script:EdepLanguage = $Language
}

function Get-EdepText([string]$Key, [object[]]$Arguments = @()) {
    $table = $EdepText[$EdepLanguage]
    $fmt = $table[$Key]
    if ($null -eq $fmt) { $fmt = $EdepText['de'][$Key] }
    if ($null -eq $fmt) { return "[$Key]" }
    if ($Arguments.Count) { return ($fmt -f $Arguments) }
    $fmt
}

$script:EdepText = @{
    de = @{
        # --- allgemein ---------------------------------------------------------
        'more'            = ' und {0} weitere'
        'mode.audit'      = 'Audit'
        'mode.enforced'   = 'Erzwingend'
        # --- ACL (EDEP-NET-10) ------------------------------------------------
        'acl.owner'       = '{0} gehört {1}'
        'acl.writable'    = '{0} schreibbar für {1}'
        'acl.unreadable'  = '{0}: ACL nicht lesbar'
        # --- L1-Prüfungen ------------------------------------------------------
        'net01.fail'      = 'Nicht aktiv oder eingehend nicht Block: {0}'
        'net01.pass'      = 'Alle Profile aktiv, eingehend Block'
        'net02.fail'      = 'Stealth-Modus deaktiviert: {0}'
        'net02.pass'      = 'Stealth-Modus aktiv (Standard)'
        'net03.fail'      = 'Ausgehend standardmäßig erlaubt: {0}. Jedes Programm darf ins Netz.'
        'net03.pass'      = 'Ausgehend Block in allen Profilen; {0} aktive ausgehende Erlaubnisregeln, keine davon uneingeschränkt'
        'net03.open'      = 'Ausgehend Block, aber eine uneingeschränkte Erlaubnisregel hebt die Sperre auf: {0}'
        'net04.fail'      = '{0} von {1} ohne ausgehende Blockregel: {2}'
        'net04.bypass'    = 'Ausgehende Authenticated-Bypass-Regeln heben Blockaden auf: {0}'
        'net04.pass'      = '{0} LOLBins ausgehend blockiert, keine Authenticated-Bypass-Regel'
        'net05.fail'      = 'Public eingehend nicht explizit gesperrt: TCP {0}'
        'net05.pass'      = 'Public eingehend gesperrt: TCP {0}'
        'net10.fail'      = '{0} freigegebene Programme für Nicht-Admins änderbar: {1}'
        'net10.unknown'   = 'Keine änderbaren Programmpfade gefunden; {0} Pfad(e) ohne Adminrechte nicht prüfbar (z. B. {1})'
        'net10.pass'      = '{0} freigegebene Programmpfade nur durch Admins änderbar'
        'id01.noadmin'    = 'App-Control-Status nur mit Adminrechten lesbar'
        'id01.denied'     = 'Zugriff verweigert (Adminrechte nötig)'
        'id01.unexpected' = 'Unerwartete CiTool-Ausgabe (OperationResult={0})'
        'id01.fail'       = 'Keine aktive, nicht-systemeigene App-Control-Richtlinie'
        'id01.pass'       = 'Aktiv: {0}'
        'id01.error'      = 'App-Control-Status nicht ermittelbar: {0}'
        'tel01.notset'    = 'Richtlinie AllowTelemetry nicht gesetzt (Windows-Standard: Optional/Full möglich)'
        'tel01.pass0'     = 'AllowTelemetry=0, wirksam: Security'
        'tel01.warn'      = 'AllowTelemetry=0, wirksam auf ''{0}'': 1 (Required) — niedrigste Stufe dieser Edition'
        'tel01.pass1'     = 'AllowTelemetry=1 (Required), niedrigste Stufe für ''{0}'''
        'tel01.fail'      = 'AllowTelemetry={0} ist nicht die niedrigste Stufe'
        'tel02.missing'   = 'Ohne ausgehende Blockregel: {0}'
        'tel02.nosid'     = 'Blockregel wirkungslos, Dienst-SID-Typ nicht RESTRICTED/UNRESTRICTED: {0}'
        'tel02.pass'      = 'Ausgehend blockiert (Dienst-SID wirksam): {0}'
        'tel03.fail'      = 'Nicht gesetzt: {0}'
        'tel03.pass'      = 'Werbe-ID und Aktivitätsverlauf per Richtlinie deaktiviert'
        'tel04.blocked'   = '{0} blockiert'
        'tel04.noallow'   = '{0} ohne Erlaubnisregel'
        'tel04.nosid'     = '{0}: Erlaubnisregel wirkungslos (Dienst-SID-Typ)'
        'tel04.defender'  = 'Defender-Plattform aktualisiert, Regel veraltet (Install-EdepL1.ps1 erneut ausführen)'
        'tel04.pass'      = 'Update- und Schutzdienste erreichbar'
        'tel04.noprobe'   = 'Regeln vorhanden, Wirkung nicht gemessen (mit -ProbeUpdates messen; unter "ausgehend Block" waren Updates in Lauf 1 trotz Regeln nicht erreichbar)'
        'tel04.probeok'   = 'Update-Suche gelungen; sie kann aus dem Zwischenspeicher stammen und beweist keine dauerhafte Erreichbarkeit'
        'tel04.probefail' = 'Update-Suche scheitert ({0}): Updates sind unter der ausgehenden Sperre nicht erreichbar'
        'log01.logblocked'= 'LogBlocked aus: {0}'
        'log01.auditpol'  = 'auditpol nicht lesbar'
        'log01.5157'      = 'Ereignis 5157 (Fehler) nicht aktiviert'
        'log01.unknown'   = 'Firewall-Log aktiv; Überwachungsrichtlinie nur mit Adminrechten lesbar'
        'log01.pass'      = 'Firewall-Log und Ereignis 5157 aktiv'
        'log02.fail'      = 'Firewall-Log auf Netzwerkpfad: {0}'
        'log02.pass'      = 'Firewall-Log lokal'
        'log06.missing'   = 'Protokoll {0} nicht vorhanden'
        'log06.disabled'  = 'Protokoll {0} deaktiviert: BITS-Umgehung (B-01) bliebe unbemerkt'
        'log06.pass'      = 'BITS-Jobs werden protokolliert ({0})'
        'ops01.pass'      = 'Sicherung vorhanden: {0}'
        'ops01.fail'      = 'Keine EDEP-Sicherung unter {0}'
        'l1.summary'      = 'EDEP {0} L1 — geprüft {1} — {2}/{3} erfüllt'
        # --- Zusatzprüfungen Audit --------------------------------------------
        'smb1.pass'       = 'SMBv1-Client-Treiber nicht installiert'
        'smb1.warn'       = 'SMBv1-Client-Treiber installiert, aber deaktiviert'
        'smb1.fail'       = 'SMBv1-Client-Treiber aktiv (Start={0})'
        'llmnr.pass'      = 'Per Richtlinie deaktiviert'
        'llmnr.fail'      = 'Aktiv (Windows-Standard)'
        'netbios.unknown' = 'Keine NetBT-Schnittstellen gefunden'
        'netbios.pass'    = 'Auf allen {0} Schnittstellen deaktiviert'
        'netbios.fail'    = 'Auf {0} von {1} Schnittstellen aktiv oder per DHCP gesteuert'
        'rdp.pass'        = 'Remotedesktop deaktiviert'
        'rdp.warn'        = 'Remotedesktop aktiv, NLA erzwungen'
        'rdp.fail'        = 'Remotedesktop aktiv ohne NLA'
        'psv2.fail'       = 'PowerShell-2.0-Engine installiert'
        'psv2.pass'       = 'PowerShell-2.0-Engine nicht vorhanden'
        'def.noadmin'     = 'Defender-Einstellungen nur mit Adminrechten lesbar'
        'def.notactive'   = 'Microsoft Defender ist nicht der aktive Virenschutz'
        'np.pass'         = 'Aktiv (Blockieren)'
        'np.warn'         = 'Nur Audit-Modus'
        'np.fail'         = 'Deaktiviert'
        'asr.pass'        = '{0} Regel(n) blockierend, {1} im Audit/Warnmodus'
        'asr.warn'        = '{0} Regel(n) nur im Audit/Warnmodus'
        'asr.fail'        = 'Keine ASR-Regel aktiv'
        'pslog.pass'      = 'Per Richtlinie aktiv'
        'pslog.fail'      = 'Nicht aktiv'
        'listen.none'     = 'Keine TCP-Dienste auf externen Adressen'
        'listen.some'     = '{0} lauschende TCP-Endpunkte: {1}'
        # --- Oberfläche --------------------------------------------------------
        'st.PASS'         = 'Erfüllt'
        'st.WARN'         = 'Teilweise'
        'st.FAIL'         = 'Offen'
        'st.UNKNOWN'      = 'Nicht prüfbar'
        'st.INFO'         = 'Info'
        'ui.headline'     = 'EDEP-Audit {0} — {1}/100 (Stufe {2})'
        'ui.counts'       = 'Offen: {0}  Teilweise: {1}  Erfüllt: {2}  Nicht prüfbar: {3}'
        'ui.noadmin'      = 'Hinweis: Ohne Adminrechte sind einige Prüfungen nicht möglich. Für ein vollständiges Ergebnis als Administrator ausführen.'
        'ui.report'       = 'Bericht: {0}'
        'html.title'      = 'EDEP-Audit: {0}'
        'html.checked'    = 'geprüft {0}'
        'html.admin'      = 'mit Adminrechten'
        'html.noadmin'    = 'ohne Adminrechte'
        'html.grade'      = 'Stufe {0}'
        'html.note'       = 'Ohne Adminrechte sind einige Prüfungen nicht möglich (App Control, Überwachungsrichtlinie, Defender). Sie fließen nicht in die Punktzahl ein. Für ein vollständiges Ergebnis PowerShell als Administrator starten.'
        'html.categories' = 'Kategorien'
        'html.findings'   = 'Befunde'
        'html.catline'    = '{0} % · {1} offen'
        'html.why'        = 'Warum:'
        'html.fix'        = 'Empfehlung:'
        'html.footer'     = 'Dieses Audit hat nichts am System verändert. Punktzahl: gewichtete Summe (Erfüllt = volles, Teilweise = halbes Gewicht; nicht prüfbare und informative Punkte zählen nicht). EDEP ist ein offener Standard: https://github.com/AndreZ1971/E.L.L.A.-Defence-Endpoint'
        'date.format'     = 'dd.MM.yyyy HH:mm'
        # --- Kategorien --------------------------------------------------------
        'cat.out'         = 'Ausgehender Verkehr'
        'cat.in'          = 'Eingehender Verkehr'
        'cat.prog'        = 'Programmkontrolle'
        'cat.tel'         = 'Telemetrie'
        'cat.log'         = 'Protokollierung'
        'cat.surface'     = 'Angriffsfläche'
        'cat.ops'         = 'Betrieb'
    }
    en = @{
        'more'            = ' and {0} more'
        'mode.audit'      = 'Audit'
        'mode.enforced'   = 'Enforced'
        'acl.owner'       = '{0} is owned by {1}'
        'acl.writable'    = '{0} is writable by {1}'
        'acl.unreadable'  = '{0}: ACL not readable'
        'net01.fail'      = 'Not enabled or inbound not Block: {0}'
        'net01.pass'      = 'All profiles enabled, inbound Block'
        'net02.fail'      = 'Stealth mode disabled: {0}'
        'net02.pass'      = 'Stealth mode active (default)'
        'net03.fail'      = 'Outbound allowed by default: {0}. Every program can reach the network.'
        'net03.pass'      = 'Outbound Block in all profiles; {0} active outbound allow rules, none of them unrestricted'
        'net03.open'      = 'Outbound Block, but an unrestricted allow rule defeats it: {0}'
        'net04.fail'      = '{0} of {1} without an outbound block rule: {2}'
        'net04.bypass'    = 'Outbound Authenticated Bypass rules override block rules: {0}'
        'net04.pass'      = '{0} LOLBins blocked outbound, no Authenticated Bypass rule'
        'net05.fail'      = 'Public inbound not explicitly blocked: TCP {0}'
        'net05.pass'      = 'Public inbound blocked: TCP {0}'
        'net10.fail'      = '{0} allowed programs can be modified by non-admins: {1}'
        'net10.unknown'   = 'No modifiable program paths found; {0} path(s) cannot be checked without admin rights (e.g. {1})'
        'net10.pass'      = '{0} allowed program paths modifiable by admins only'
        'id01.noadmin'    = 'App Control status readable with admin rights only'
        'id01.denied'     = 'Access denied (admin rights required)'
        'id01.unexpected' = 'Unexpected CiTool output (OperationResult={0})'
        'id01.fail'       = 'No active, non-system App Control policy'
        'id01.pass'       = 'Active: {0}'
        'id01.error'      = 'App Control status could not be determined: {0}'
        'tel01.notset'    = 'Policy AllowTelemetry not set (Windows default: Optional/Full possible)'
        'tel01.pass0'     = 'AllowTelemetry=0, effective: Security'
        'tel01.warn'      = 'AllowTelemetry=0, effective on ''{0}'': 1 (Required), the lowest level of this edition'
        'tel01.pass1'     = 'AllowTelemetry=1 (Required), lowest level for ''{0}'''
        'tel01.fail'      = 'AllowTelemetry={0} is not the lowest level'
        'tel02.missing'   = 'Without an outbound block rule: {0}'
        'tel02.nosid'     = 'Block rule ineffective, service SID type not RESTRICTED/UNRESTRICTED: {0}'
        'tel02.pass'      = 'Blocked outbound (service SID effective): {0}'
        'tel03.fail'      = 'Not set: {0}'
        'tel03.pass'      = 'Advertising ID and activity history disabled by policy'
        'tel04.blocked'   = '{0} blocked'
        'tel04.noallow'   = '{0} without allow rule'
        'tel04.nosid'     = '{0}: allow rule ineffective (service SID type)'
        'tel04.defender'  = 'Defender platform updated, rule outdated (run Install-EdepL1.ps1 again)'
        'tel04.pass'      = 'Update and protection services reachable'
        'tel04.noprobe'   = 'Rules present, effect not measured (measure with -ProbeUpdates; under "outbound block" updates were unreachable in run 1 despite the rules)'
        'tel04.probeok'   = 'Update search succeeded; it may come from the cache and does not prove lasting reachability'
        'tel04.probefail' = 'Update search fails ({0}): updates are not reachable under the outbound block'
        'log01.logblocked'= 'LogBlocked off: {0}'
        'log01.auditpol'  = 'auditpol not readable'
        'log01.5157'      = 'Event 5157 (failure) not enabled'
        'log01.unknown'   = 'Firewall log active; audit policy readable with admin rights only'
        'log01.pass'      = 'Firewall log and event 5157 active'
        'log02.fail'      = 'Firewall log on a network path: {0}'
        'log02.pass'      = 'Firewall log is local'
        'log06.missing'   = 'Log {0} not present'
        'log06.disabled'  = 'Log {0} disabled: the BITS bypass (B-01) would go unnoticed'
        'log06.pass'      = 'BITS jobs are logged ({0})'
        'ops01.pass'      = 'Backup present: {0}'
        'ops01.fail'      = 'No EDEP backup under {0}'
        'l1.summary'      = 'EDEP {0} L1 — checked {1} — {2}/{3} passed'
        'smb1.pass'       = 'SMBv1 client driver not installed'
        'smb1.warn'       = 'SMBv1 client driver installed but disabled'
        'smb1.fail'       = 'SMBv1 client driver active (Start={0})'
        'llmnr.pass'      = 'Disabled by policy'
        'llmnr.fail'      = 'Enabled (Windows default)'
        'netbios.unknown' = 'No NetBT interfaces found'
        'netbios.pass'    = 'Disabled on all {0} interfaces'
        'netbios.fail'    = 'Enabled or DHCP-controlled on {0} of {1} interfaces'
        'rdp.pass'        = 'Remote Desktop disabled'
        'rdp.warn'        = 'Remote Desktop enabled, NLA enforced'
        'rdp.fail'        = 'Remote Desktop enabled without NLA'
        'psv2.fail'       = 'PowerShell 2.0 engine installed'
        'psv2.pass'       = 'PowerShell 2.0 engine not present'
        'def.noadmin'     = 'Defender settings readable with admin rights only'
        'def.notactive'   = 'Microsoft Defender is not the active antivirus'
        'np.pass'         = 'Enabled (block)'
        'np.warn'         = 'Audit mode only'
        'np.fail'         = 'Disabled'
        'asr.pass'        = '{0} rule(s) blocking, {1} in audit/warn mode'
        'asr.warn'        = '{0} rule(s) in audit/warn mode only'
        'asr.fail'        = 'No ASR rule active'
        'pslog.pass'      = 'Enabled by policy'
        'pslog.fail'      = 'Not enabled'
        'listen.none'     = 'No TCP services on external addresses'
        'listen.some'     = '{0} listening TCP endpoints: {1}'
        'st.PASS'         = 'Passed'
        'st.WARN'         = 'Partial'
        'st.FAIL'         = 'Open'
        'st.UNKNOWN'      = 'Not checkable'
        'st.INFO'         = 'Info'
        'ui.headline'     = 'EDEP audit {0} — {1}/100 (grade {2})'
        'ui.counts'       = 'Open: {0}  Partial: {1}  Passed: {2}  Not checkable: {3}'
        'ui.noadmin'      = 'Note: some checks are not possible without admin rights. Run as administrator for a complete result.'
        'ui.report'       = 'Report: {0}'
        'html.title'      = 'EDEP audit: {0}'
        'html.checked'    = 'checked {0}'
        'html.admin'      = 'with admin rights'
        'html.noadmin'    = 'without admin rights'
        'html.grade'      = 'Grade {0}'
        'html.note'       = 'Some checks are not possible without admin rights (App Control, audit policy, Defender). They are excluded from the score. Start PowerShell as administrator for a complete result.'
        'html.categories' = 'Categories'
        'html.findings'   = 'Findings'
        'html.catline'    = '{0} % · {1} open'
        'html.why'        = 'Why:'
        'html.fix'        = 'Recommendation:'
        'html.footer'     = 'This audit did not change the system. Score: weighted sum (passed = full, partial = half weight; not checkable and informational items do not count). EDEP is an open standard: https://github.com/AndreZ1971/E.L.L.A.-Defence-Endpoint'
        'date.format'     = 'yyyy-MM-dd HH:mm'
        'cat.out'         = 'Outbound traffic'
        'cat.in'          = 'Inbound traffic'
        'cat.prog'        = 'Program control'
        'cat.tel'         = 'Telemetry'
        'cat.log'         = 'Logging'
        'cat.surface'     = 'Attack surface'
        'cat.ops'         = 'Operations'
    }
}
